//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filme()
        {
            this.Atuacao = new HashSet<Atuacao>();
            this.LongaMetragem = new HashSet<LongaMetragem>();
        }
    
        public int id { get; set; }
        public decimal verba { get; set; }
        public System.DateTime dtGravacaoInicio { get; set; }
        public System.DateTime dtGravacaoFim { get; set; }
        public Nullable<int> idDireto { get; set; }
        public Nullable<int> idProdutor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atuacao> Atuacao { get; set; }
        public virtual Diretor Diretor { get; set; }
        public virtual Documentario Documentario { get; set; }
        public virtual Produtor Produtor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LongaMetragem> LongaMetragem { get; set; }
    }
}
